### ISSUE TITLE
ipynb examples need help- gbts and plotly not imported

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#10]
I didn't find Grand Bay/py in the repo, and it's needed in the aqd_make_press_ac.ipynb example, so it fails on the "import gbts" line.  Not sure where plotly comes from, but it doesn't import successfully either on my computer.  Perhaps it should go in the env, so python will know it needs it?

**Comment by emontgomery-usgs** [comment]
OK, I see the grandbay repo is needed to run the example ipynb.  cloned it to my local place.

Plotly is a separate package, not installed by default in anaconda.  "Conda install plotly" gets it for the local system

**Comment by dnowacki-usgs** [comment]
Right. I updated the aqd atmos script to be less reliant on other repos. In general it will be up to the user to obtain the met data from wherever and get it into netcdf (or otherwise make it available in the notebook) for the atmos correction. Does that make sense?

**Comment by dnowacki-usgs** [comment]
After our discussion, I'm going to close this. Please reopen, or start a new issue, if anything further comes up. Thanks!

**Comment by emontgomery-usgs** [comment]
I got the most recent version, and it's way better pointing to the ./examples directory and working in an more generic way.  It worked like a champ, up til step 6, when I got this- it looks like it doesn't know what RAW is.

NameError                                 Traceback (most recent call last)
<ipython-input-6-72436498048e> in <module>()
      1 plt.figure(figsize=(10,8))
----> 2 RAW['Pressure'].plot()
      3 VEL['P_1ac'].plot()
      4 plt.show()

NameError: name 'RAW' is not defined

<matplotlib.figure.Figure at 0xb0e2160>

**Comment by dnowacki-usgs** [comment]
Sorry, there needed to be an extra
`RAW, fildir = load_raw(site, dep, basedir)`
in the Load clean data cell. You can add that, or re-pull the repo to get the fix.

**Comment by emontgomery-usgs** [comment]
Great, it runs now.  Thanks!

However, I get this warning- is it important? thanks!
C:\Users\emontgomery\AppData\Local\Continuum\Miniconda3\envs\IOOS\lib\site-packages\xarray\plot\utils.py:51: FutureWarning: 'pandas.tseries.converter.register' has been moved and renamed to 'pandas.plotting.register_matplotlib_converters'. 
  converter.register()
