### ISSUE TITLE
atmospheric file format description someplace?

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#11]
gbts.read_nerrs() calls a csv file containing atmospheric data to use in correcting pressure data.  Not all atmospheric data will be in the same format, but columns could be organized to match a spec if given.  I'm trying to run this chunk of code on data from West Falmouth Harbor - the columns of this data are sample #, date time, press, temp,,,,,, (5 empty columns at the end).  Since the csv file referenced isn't provided, it's hard to know how to reformat the data.

**Comment by dnowacki-usgs** [comment]
We already discussed this a bit, but there are details about the atmos pressure file format here:
http://stglib.readthedocs.io/en/latest/atmos.html

**Comment by emontgomery-usgs** [comment]
@dnowacki-usgs , The doc is helpful, but please supply a sample atmos.cdf.  Also needed is how you got to the offset of -10.25.

**Comment by emontgomery-usgs** [comment]
Stepping through aqd_make_pres_ac.ipynb is helping figure out what some of this does.  I'm sort of surprised the resolution of the original gndcrmet file is just 1mb...  Still not much closer to writing my own atmos.cdf from another source of raw data.

**Comment by dnowacki-usgs** [comment]
Hi Ellyn, Can you check out http://stglib.readthedocs.io/en/latest/atmos.html and tell me if this is sufficient, or what else you'd like to see? Thanks.

**Comment by dnowacki-usgs** [comment]
Going to close this, but please let me know if the docs can be clearer.
