### ISSUE TITLE
syntax to import core/utils?

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#33]
@dnowacki-usgs 
I'm trying to use methods from utils.py in core in a new ipynb, and followed the syntax in cdf2nc.py, but get errors.  Please set me straight- thanks!

ValueError                                Traceback (most recent call last)
<ipython-input-4-55766b093429> in <module>()
      1 import xarray as xr
      2 import stglib
----> 3 from ..core import utils

ValueError: attempted relative import beyond top-level package

**Comment by dnowacki-usgs** [comment]
When you import `stglib` you get `utils` for free, so you can do something like

```
import stglib
ds = stglib.utils.trim_max_wh(ds)
```

**Comment by emontgomery-usgs** [comment]
thanks!
