### ISSUE TITLE
runaqdhdr2cdf.py doesn't like '30 m' in read_aqd_hdr

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#4]
Hi-

I got this error when trying to use your code to re-run 983.
![image](https://user-images.githubusercontent.com/1771422/39009982-34bfeb76-43db-11e8-8e9e-d01a7d34f5b0.png)
If you have time, would you show me a bit more about how to go about debugging?

So far, all I can tell is that it doesn't like something it found in the Aqd header- the '30M' isn't in either of argument files.

**Comment by emontgomery-usgs** [comment]
from Dan in email:
Yes, this is failing on the “mm” units in the .hdr file, in the cell size line. This appears to be an HR deployment, which stglib does not yet support

**Comment by dnowacki-usgs** [comment]
This now gives a more useful error when encountering HR datasets
