### ISSUE TITLE
Make new release and available on conda-forge

### ISSUE THREAD

**Issue by rsignell-usgs** [dnowacki-usgs/stglib#50]
I know that stglib is under constant development, but the philosophy of conda-forge is release early, release often.    Would be nice to have it there, if only to do `conda install stglib --only-deps`

**Comment by dnowacki-usgs** [comment]
Rich is there a good guide for preparing a package for conda-forge? I like the idea of getting on conda-forge, but I remember looking months ago and it looked like too much effort to get spun up at the time.

**Comment by dnowacki-usgs** [comment]
I invite you to check out https://anaconda.org/conda-forge/stglib

**Comment by ssuttles-usgs** [comment]
Nice work!


Steven Suttles
U. S. Geological Survey, Coastal and Marine Geology
384 Woods Hole Road, Woods Hole, MA 02543-1598
ssuttles@usgs.gov<mailto:ssuttles@usgs.gov>
(508) 457-2228
________________________________

**Comment by dnowacki-usgs** [comment]
Closing. We should discuss how often to issue releases.

**Comment by ssuttles-usgs** [comment]
Yes. Certainly when the straight to CF code is ready, and then my thought is incrementally when significant numbers of new instruments are added and the code thoroughly vetted. I would think it would be on the order of 1 or 2/yr?


Steven Suttles
U. S. Geological Survey, Coastal and Marine Geology
384 Woods Hole Road, Woods Hole, MA 02543-1598
ssuttles@usgs.gov<mailto:ssuttles@usgs.gov>
(508) 457-2228
________________________________
