### ISSUE TITLE
tracking the zeroing of pressure sensors

### ISSUE THREAD

**Issue by mmartini-usgs** [dnowacki-usgs/stglib#51]
This came up today - most of the time now we want to make atmospheric pressure corrections to the recorded pressure data from most of the instruments processed by this library.  Some might consider such a correction interpretive - depending on the location of the deployment.  Either way, the information necessary to make the decision to correct needs to be available to the code.  Some of this is already provided for in .yml files.

The aquadopp and EXO .yml file has 
zeroed_pressure: 'Yes' # was pressure zeroed before deployment
P_1ac_note: 'Corrected for variations in atmospheric pressure using Grand Bay NERR met station (GNDCRMET).'

The dwave has
P_1ac_note: 'Corrected for variations in atmospheric pressure using Grand Bay NERR met station (GNDCRMET).'
and should have a zeroed pressure note.

We should add the date, time, time zone and location the zeroing was done, if done, so that the pressure can be looked up, and perhaps even the local measurement of atmospheric pressure with the tag of the weather station used (Chatham, say is KCQX).

Tell me what you think!

**Comment by dnowacki-usgs** [comment]
In my mind `zeroed_pressure` is distinct from atmospheric compensation; additionally the sensor doesn't have to be zeroed to be corrected for atmospheric. My workflow is almost always to inspect the reading in air just before deployment and just after recovery and subtract the average of those values as part of the atmospheric compensation routine. An additional issue is that Aquadopps do not record negative pressure so I'm always suspicious when the sensor reads zero, as we don't know how much lower than zero it actually was that particular day.

**Comment by mmartini-usgs** [comment]
Yes.  And these data get served publicly.  Consider the person who did not handle the instrument, and/or had no involvement in the data collection.  Someone who does not have access to the instrument record.  So even though the dwave doesn't get zeroed, if one doesn't know dwaves, they should not have to guess.  Including `zeroed_pressure` is a clear indication of what was done to the instrument at deployment, or not.  From there, it's up to the analyst to decide what they want to do.

**Comment by dnowacki-usgs** [comment]
Got it. Yes, I agree that greater detail on what was done should be encouraged! Are you thinking that should be in `P_1ac_note`? Or a change to `zeroed_pressure`?

**Comment by mmartini-usgs** [comment]
I guess the fundamental issue is to note - was the pressure sensor zeroed.  From that one would know what to do to generate, or not generate, P_1ac.  It's good in the existing aquadopp code as a global attribute, e.g. an indication of how the instrument, as a whole, was set up.  To be consistent, for other instruments where zeroing, or lack there of, has bearing on how people may use the data, we need a global attribute.  May as well use zeroed_pressure.
