### ISSUE TITLE
Output of a sample test run of runaqdhdr2cdf.py on 10104aqd is all 0's- why?

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#6]
I had a seemingly successful run of an example from MVCO14 with your code but the matrix data in the -a is wrong.  The program is incredibly fast though.  output files attached.

(ioos) C:\home\data\proc\MVCO2014\1010_QD1_21m\aqd_11275\raw>python runaqdhdr2cdf.py ../../../glob_att1010.txt 10104_config.txt
Loading ASCII files
Insrument orientation: DOWN
Center_first_bin = 0.400000
bin_size = 0.200000
bin_count = 12.000000
User instructed that instrument was pointing DOWN
Time shifted by: 65 s
Finished writing data to 10104aqd-raw.cdf

(ioos) C:\home\data\proc\MVCO2014\1010_QD1_21m\aqd_11275\raw>python /Users/emontgomery/python_progs/DNstg/stglib/scripts/runaqdcdf2nc.py 10104aqd-raw.cdf
first burst in full file: 2014-07-01T04:00:00.000000000
last burst in full file: 2014-09-24T17:30:00.000000000
Clipping data using Deployment_date and Recovery_date
first burst in trimmed file: 2014-07-01T04:00:00.000000000
last burst in trimmed file: 2014-09-23T23:50:00.000000000
User instructed that instrument was pointing DOWN
Data are in XYZ coordinates; transforming to Earth coordinates
Rotating heading and horizontal velocities by -14.800000 degrees
Using NON-atmospherically corrected pressure to trim
Done writing netCDF file 10104aqd-a.nc

The resulting -a.nc file opened in ncBrowse and has reasonable looking data in P_1 and hdg_1215, but u and v both just showed up as black.  I opened both in malab both u & v contain all 0's.  There is variation in the VEL* variables in the CDF file, so it seems good that far...  Not sure where to look for what's wrong- pls advise.

**Comment by dnowacki-usgs** [comment]
Can you send the config yaml and glob atts file? I can grab the data off stg_field and see if I can reproduce. Thanks.

**Comment by dnowacki-usgs** [comment]
Should be all set. I'd only been processing beam data until now!
