### ISSUE TITLE
documentation of config file changed on 4/6

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#7]
Yesterday I got the example config file for Aqd from http://stglib.readthedocs.io/en/latest/config.html, now an exo config file is there.  Was this intentional?

**Comment by emontgomery-usgs** [comment]
I think the answer was no.  On 4/19, there are instrument specific configuration file examples for Aqdopp, exo, d|wave.

**Comment by emontgomery-usgs** [comment]
I did- see note above in comment 2 closing issue.

**Comment by dnowacki-usgs** [comment]
Whoops! I was too quick to respond.
