### ISSUE TITLE
how to edit content on http://stglib.readthedocs.io/en/latest/aqd.html

### ISSUE THREAD

**Issue by emontgomery-usgs** [dnowacki-usgs/stglib#8]
I believe you said the documentation was mostly auto generated from comments in the code, so I'm not sure where or how to add content like- "4/19/18- only works on up-looking non-HR instruments".  I tried clicking the edit on git-hub link and the file it was looking for was not found.

It would also be good to put something like this in the processing overview: "the only modification needed to the programs is changing sys.path.insert to the local path to stglib.  After that's done, the programs should run without needing additional modification."

**Comment by dnowacki-usgs** [comment]
Ugh, yeah, despite the nifty integration with GitHub on Read The Docs, the "edit on GitHub" links are broken; this is a known issue apparently. The raw source files from which the RTD pages are generated are located here: 
https://github.com/dnowacki-usgs/stglib/tree/master/doc

For the docs, you can make the changes on your local machine and make a pull request that way, or you can use the online editor (click pencil icon in upper right corner).

**Comment by dnowacki-usgs** [comment]
If you see issues that could use clarification, I'd be happy to have your input and/or changes... either as suggestions here, or as PRs via the online editor.
